export const ORDER_STATE_TRANSITIONS = {
  PENDING: ['PAID', 'CANCELLED'],
  PAID: ['PARTIALLY_REFUNDED', 'REFUNDED'],
  PARTIALLY_REFUNDED: ['PARTIALLY_REFUNDED', 'REFUNDED'],
  REFUNDED: [],
  CANCELLED: [],
};